Controllers/EstadisticasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sistema_Gestion_Negocio_ASP.NET_MVC.Context;
using Sistema_Gestion_Negocio_ASP.NET_MVC.Helper;

namespace Sistema_Gestion_Negocio_ASP.NET_MVC.Controllers
{
    public class EstadisticasController : Controller
    {
        NegocioContext context;
        public ILogger<EstadisticasController> logger;

        public EstadisticasController(NegocioContext _context, ILogger<EstadisticasController> _logger)
        {
            context = _context;
            logger = _logger;
        }


        public IActionResult mostrarEstadisticas()
        {

            string id = UsuarioHelper.ObtenerNegocioIdDelUsuario(HttpContext);

            ViewBag.negocioId = id;

            return View();
        }

    }
}

Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Sistema_Gestion_Negocio_ASP.NET_MVC.Context;
using Sistema_Gestion_Negocio_ASP.NET_MVC.Helper;

namespace Sistema_Gestion_Negocio_ASP.NET_MVC.Controllers
{
    public class ProductoController : Controller
    {
        NegocioContext context;
        public ILogger<LoginController> logger;

        public ProductoController (NegocioContext _context, ILogger<LoginController> _logger)
        {
            context = _context;
            logger = _logger;
        }

        public IActionResult Productos()
        {
            string negocioIdUsuario = UsuarioHelper.ObtenerNegocioIdDelUsuario(HttpContext);

            ViewBag.negocioId = negocioIdUsuario;

            return View();
        }
    }
}

Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;
using Sistema_Gestion_Negocio_ASP.NET_MVC.Context;
using Sistema_Gestion_Negocio_ASP.NET_MVC.Helper;

namespace Sistema_Gestion_Negocio_ASP.NET_MVC.Controllers
{
    public class VentaController : Controller
    {

        NegocioContext context;
        public ILogger<VentaController> logger;

        public VentaController(NegocioContext _context, ILogger<VentaController> _logger)
        {
            context = _context;
            logger = _logger;
        }



        public IActionResult RegistrarVenta()
        {
            string negocioIdUsuario = UsuarioHelper.ObtenerNegocioIdDelUsuario(HttpContext);
            string usuarioId = UsuarioHelper.ObtenerUsuarioId(HttpContext);

            ViewBag.negocioId = negocioIdUsuario;
            ViewBag.usuarioId = usuarioId;
            ViewBag.formasDePago = context.FormasPago.ToList();
            return View();
        }

        public IActionResult Ventas()
        {
            string negocioIdUsuario = UsuarioHelper.ObtenerNegocioIdDelUsuario(HttpContext);

            ViewBag.negocioId = negocioIdUsuario;

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema_Gestion_Negocio_ASP.NET_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sistema_Gestion_Negocio_ASP.NET_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema_Gestion_Negocio_ASP.NET_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Sistema_Gestion_Negocio_ASP.NET_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutInicio.cshtml
@{
    Layout = null;
}

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - NegociApp</title>

    <link rel="icon" href="~/img/icono.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sistema_Gestion_Negocio_ASP.NET_MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/inicio.css" />

</head>
<body class="inicio-body">

    @RenderBody()

</body>
</html>

Views/Shared/_LayoutLogin.cshtml
@{
    Layout = null;  
}
@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - NegociApp</title>

    <link rel="icon" href="~/img/icono.ico" type="image/x-icon">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sistema_Gestion_Negocio_ASP.NET_MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login.css" />
    <link rel="stylesheet" href="~/css/RegistroUsuario.css" />
    <link rel="stylesheet" href="~/css/error.css" />

</head>
<body class="login-body">
    
        @RenderBody() 
    
</body>
</html>

Views/Shared/_LayoutNavbar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NegociApp</title>

    <link rel="icon" href="~/img/icono.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sistema_Gestion_Negocio_ASP.NET_MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/EstiloNavbar.css" />
    <link rel="stylesheet" href="~/css/RegistrarVenta.css" />
    <link rel="stylesheet" href="~/css/MiNegocio.css" />
    <link rel="stylesheet" href="~/css/EditarNegocio.css" />
    <link rel="stylesheet" href="~/css/Producto.css" />
    <link rel="stylesheet" href="~/css/Ventas.css" />
    <link rel="stylesheet" href="~/css/Estadisticas.css" />
    <link rel="stylesheet" href="~/css/AgregarNegocio.css" />
    <link rel="stylesheet" href="~/css/Negocios.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="navBarContainer">

        <button class="toggle-sidebar" onclick="toggleSidebar()">
            <i class="bi bi-list"></i>
        </button>

        <!-- Sidebar -->
        <nav class="sidebar">
            <div class="logoContainer">
                <img class="img-logo" src="~/img/NegociAppLogoTransparente.png" />
            </div>
            

            @if (User.IsInRole("AdministradorNegocio") || User.IsInRole("Empleado") || User.IsInRole("Invitado"))
            {
                <a asp-area="" asp-controller="Venta" asp-action="RegistrarVenta"><i class="bi bi-cart-plus fs-4"></i> Registrar venta</a>
            }

            
            @if (User.IsInRole("AdministradorGeneral"))
            {
                <a asp-area="" asp-controller="Negocio" asp-action="Negocios"><i class="bi bi-shop-window fs-4"></i> Negocios</a>
            }
            @if (User.IsInRole("AdministradorNegocio") || User.IsInRole("Invitado"))
            {
                <a asp-area="" asp-controller="Negocio" asp-action="MiNegocio"><i class="bi bi-shop-window fs-4"></i> Mi negocio</a>
            }
            
            
            @if (User.IsInRole("AdministradorNegocio") || User.IsInRole("Empleado") || User.IsInRole("Invitado"))
            {
                <a asp-area="" asp-controller="Producto" asp-action="Productos"><i class="bi bi-tags fs-4"></i> Productos</a>
                <a asp-area="" asp-controller="Venta" asp-action="Ventas"><i class="bi bi-currency-dollar fs-4"></i> Ventas</a>
                <a asp-area="" asp-controller="Estadisticas" asp-action="mostrarEstadisticas"><i class="bi bi-graph-up fs-4"></i> Estadísticas</a>
            }
          
            @if (User.IsInRole("AdministradorNegocio") || User.IsInRole("Empleado") || User.IsInRole("AdministradorGeneral"))
            {
                <a class="cerrar-sesion" asp-area="" asp-controller="Login" asp-action="CerrarSesion"><i class="bi bi-box-arrow-right fs-4"></i> Cerrar sesión</a>
            }

            @if (User.IsInRole("Invitado"))
            {
                <a class="cerrar-sesion" asp-area="" asp-controller="Invitado" asp-action="CerrarSesionInvitado"><i class="bi bi-box-arrow-right fs-4"></i> Cerrar sesión</a>
            }


        </nav>

        <!-- Contenido principal y footer -->
        <div class="main-content">

            <div class="user-bar d-flex justify-content-end align-items-center mb-3">
                <div class="user-info px-3 py-1 d-flex align-items-center rounded">
                    <i class="bi bi-person-circle fs-4 me-2"></i>
                    <span class="fw-semibold">@User.Identity.Name</span>
                </div>
            </div>

            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)



    <script>
        function toggleSidebar() {
            document.querySelector('.sidebar').classList.toggle('active');
        }

        // Cerrar sidebar al hacer clic en un link (solo en celular)
        document.querySelectorAll('.sidebar a').forEach(link => {
            link.addEventListener('click', () => {
                if (window.innerWidth <= 768) {
                    document.querySelector('.sidebar').classList.remove('active');
                }
            });
        });
    </script>

</body>
</html>